# Generated by Django 5.1.4 on 2025-03-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('she', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('INSPECTOR', 'INSPECTOR'), ('SUPERVISOR', 'SUPERVISOR'), ('SAFETY', 'SAFETY'), ('SHIFT-SUPERVISOR', 'SHIFT-SUPERVISOR')], default='USER', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='she.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
