# Generated by Django 5.1.4 on 2025-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('OPERATOR', 'OPERATOR'), ('INSPECTOR', 'INSPECTOR'), ('SUPERVISOR', 'SUPERVISOR')], default='USER', max_length=20)),
            ],
        ),
    ]
