# Generated by Django 5.1.4 on 2025-01-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
    ]
