# Generated by Django 5.1.4 on 2025-02-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('issue', '0006_alter_department_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('INSPECTOR', 'INSPECTOR'), ('SUPERVISOR', 'SUPERVISOR'), ('SAFETY', 'SAFETY'), ('SHIFT-SUPERVISOR', 'SHIFT-SUPERVISOR')], default='USER', max_length=20),
        ),
    ]
