# Generated by Django 5.1.4 on 2025-03-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('job', '0001_initial'),
        ('machine', '0001_initial'),
        ('misc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='job_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='job.jobtest'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='misc.shift'),
        ),
        migrations.AddField(
            model_name='firstoff',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_offs', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='lamination',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lamination', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_processes', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.conformity'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_on_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
        migrations.AddField(
            model_name='semiwaste',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_semi_wastes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semiwaste',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_semi_wastes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semiwaste',
            name='job_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='semi_wastes', to='job.jobtest'),
        ),
        migrations.AddField(
            model_name='substrate',
            name='lamination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='substrates', to='assessment.lamination'),
        ),
        migrations.AddField(
            model_name='substrate',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.rawmaterial'),
        ),
        migrations.AddField(
            model_name='firstoff',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
        ),
        migrations.AddField(
            model_name='viscosity',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viscosities', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='viscosity',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viscosities', to='misc.color'),
        ),
        migrations.AddField(
            model_name='viscosity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_viscosities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waste',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='waste',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
        migrations.AddField(
            model_name='waste',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='onprocess',
            unique_together={('assessment', 'sample_no')},
        ),
        migrations.AlterUniqueTogether(
            name='substrate',
            unique_together={('lamination', 'raw_material')},
        ),
    ]
