# Generated by Django 5.1.4 on 2025-01-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('job', '0001_initial'),
        ('machine', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='job_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobtest'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
        migrations.AddField(
            model_name='firstoff',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_offs', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_processes', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.conformity'),
        ),
        migrations.AddField(
            model_name='firstoff',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
        ),
    ]
