# Generated by Django 5.1.4 on 2025-01-15 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_date_alter_assessment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onprocess',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 15)),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='time',
            field=models.TimeField(default=16),
        ),
    ]
