# Generated by Django 5.1.4 on 2025-01-15 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_onprocess_date_alter_onprocess_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='time',
            field=models.TimeField(),
        ),
    ]
