# Generated by Django 5.1.4 on 2025-01-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessment_date_alter_assessment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onprocess',
            name='date',
        ),
        migrations.RemoveField(
            model_name='onprocess',
            name='time',
        ),
    ]
