# Generated by Django 5.1.4 on 2025-01-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_remove_onprocess_date_remove_onprocess_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(blank=True, choices=[('FIRST-OFF', 'FIRST-OFF'), ('ON-PROCESS', 'ON-PROCESS')], max_length=20, null=True),
        ),
    ]
