# Generated by Django 5.1.4 on 2025-01-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onprocess',
            name='sample_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
