# Generated by Django 5.1.4 on 2025-01-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_onprocess_sample_no_onprocess_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onprocess',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.conformity'),
        ),
    ]
