# Generated by Django 5.1.4 on 2025-01-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_onprocess_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conformity',
            options={'ordering': ['name'], 'verbose_name_plural': 'conformities'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name']},
        ),
    ]
