# Generated by Django 5.1.4 on 2025-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_conformity_options_alter_test_options'),
        ('misc', '0006_alter_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='onprocess',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
    ]
