# Generated by Django 5.1.4 on 2025-01-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_onprocess_shift'),
        ('machine', '0003_machine_viscosity_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onprocess',
            options={'ordering': ['-time']},
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='assessment.assessment')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
        ),
    ]
