# Generated by Django 5.1.4 on 2025-01-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_alter_onprocess_options_waste'),
        ('misc', '0006_alter_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
