# Generated by Django 5.1.4 on 2025-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_waste_shift_alter_waste_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
