# Generated by Django 5.1.4 on 2025-01-27 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_alter_waste_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='onprocess',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='action',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
