# Generated by Django 5.1.4 on 2025-01-27 13:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_onprocess_date_alter_onprocess_action'),
        ('misc', '0006_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Viscosity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(blank=True, max_length=30, null=True)),
                ('value', models.FloatField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viscosities', to='assessment.assessment')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viscosities', to='misc.color')),
            ],
        ),
    ]
