# Generated by Django 5.1.4 on 2025-01-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_assessment_date_viscosity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viscosity',
            options={'verbose_name_plural': 'viscosities'},
        ),
    ]
