# Generated by Django 5.1.4 on 2025-01-29 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_viscosity_created_at_viscosity_created_by'),
        ('job', '0008_jobtest_artwork'),
        ('misc', '0007_alter_color_viscosity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('tag_no', models.CharField(max_length=30)),
                ('approved_quantity', models.PositiveIntegerField(default=0)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_semi_wastes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_semi_wastes', to=settings.AUTH_USER_MODEL)),
                ('job_test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='job.jobtest')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.shift')),
            ],
            options={
                'verbose_name_plural': 'semi_wastes',
            },
        ),
    ]
