# Generated by Django 5.1.4 on 2025-01-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_semiwaste'),
        # ('misc', '0008_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='semiwaste',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semiwaste',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_wastes', to='misc.shift'),
        ),
    ]
