# Generated by Django 5.1.4 on 2025-01-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_semiwaste_remark_alter_semiwaste_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semiwaste',
            name='shift',
        ),
    ]
