# Generated by Django 5.1.4 on 2025-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_remove_semiwaste_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semiwaste',
            name='tag_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
