# Generated by Django 5.1.4 on 2025-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_alter_semiwaste_tag_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='semiwaste',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='semiwaste',
            name='remark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
