# Generated by Django 5.1.4 on 2025-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_semiwaste_comment_alter_semiwaste_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='semiwaste',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('APPROVED', 'APPROVED')], default='OPEN', max_length=20),
        ),
    ]
