# Generated by Django 5.1.4 on 2025-01-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_semiwaste_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semiwaste',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20),
        ),
    ]
