# Generated by Django 5.1.4 on 2025-02-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_alter_semiwaste_status'),
        ('misc', '0009_delete_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply_structure', models.PositiveIntegerField(default=2)),
                ('mechanism', models.CharField(choices=[('SOLVENTLESS', 'SOLVENTLESS'), ('SOLVENT-BASED', 'SOLVENT-BASED')], max_length=30, null=True)),
                ('mixing_ratio', models.CharField(max_length=20, null=True)),
                ('adhesive', models.CharField(blank=True, max_length=50, null=True)),
                ('adhesive_batch_no', models.CharField(blank=True, max_length=30, null=True)),
                ('hardner', models.CharField(blank=True, max_length=50, null=True)),
                ('hardner_batch_no', models.CharField(blank=True, max_length=30, null=True)),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laminations', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=30, null=True)),
                ('lamination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='substrates', to='assessment.lamination')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.rawmaterial')),
            ],
        ),
    ]
