# Generated by Django 5.1.4 on 2025-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0026_lamination_substrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamination',
            name='adhesive',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='adhesive_batch_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='hardner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='hardner_batch_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='mechanism',
            field=models.CharField(choices=[('SOLVENTLESS', 'SOLVENTLESS'), ('SOLVENT-BASED', 'SOLVENT-BASED')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='supplier',
            field=models.CharField(max_length=50),
        ),
    ]
