# Generated by Django 5.1.4 on 2025-02-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_alter_lamination_adhesive_and_more'),
        ('job', '0009_alter_jobtest_status'),
        ('misc', '0009_delete_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='job_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='job.jobtest'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='misc.shift'),
        ),
    ]
