# Generated by Django 5.1.4 on 2025-02-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0028_alter_assessment_job_test_alter_assessment_shift'),
        ('misc', '0009_delete_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrate',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.rawmaterial'),
        ),
    ]
