# Generated by Django 5.1.4 on 2025-02-05 06:32

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0029_alter_substrate_raw_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lamination",
            name="mixing_ratio",
            field=models.CharField(
                max_length=20, validators=[main.validators.validate_ratio_format]
            ),
        ),
    ]
