# Generated by Django 5.1.4 on 2025-02-06 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0030_alter_lamination_mixing_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
