# Generated by Django 5.1.4 on 2025-02-07 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_alter_assessment_date_alter_onprocess_date'),
        ('job', '0009_alter_jobtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='semiwaste',
            name='job_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='semi_wastes', to='job.jobtest'),
        ),
    ]
