# Generated by Django 5.1.4 on 2025-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_alter_assessment_date_alter_semiwaste_job_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='mechanism',
            field=models.CharField(choices=[('SOLVENTLESS', 'SOLVENTLESS'), ('SOLVENT-BASE', 'SOLVENT-BASE')], max_length=30),
        ),
    ]
