# Generated by Django 5.1.4 on 2025-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0033_test_critical_alter_lamination_mechanism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoff',
            name='value',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
