# Generated by Django 5.1.4 on 2025-02-13 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_alter_firstoff_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onprocess',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='waste',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='onprocess',
            name='date',
        ),
        migrations.RemoveField(
            model_name='onprocess',
            name='time',
        ),
        migrations.AddField(
            model_name='firstoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstoff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='semiwaste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viscosity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='waste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
