# Generated by Django 5.1.4 on 2025-02-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0035_alter_onprocess_options_alter_waste_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lamination',
            old_name='mechanism',
            new_name='type',
        ),
    ]
