# Generated by Django 5.1.4 on 2025-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_rename_mechanism_lamination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrate',
            name='no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
