# Generated by Django 5.1.4 on 2025-02-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0037_substrate_no'),
        ('misc', '0011_alter_color_name_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substrate',
            options={'ordering': ['no']},
        ),
        migrations.AlterUniqueTogether(
            name='substrate',
            unique_together={('lamination', 'raw_material')},
        ),
    ]
