# Generated by Django 5.1.4 on 2025-02-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0038_alter_substrate_options_and_more'),
        ('misc', '0011_alter_color_name_alter_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onprocess',
            name='action',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_on_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onprocess',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
    ]
