# Generated by Django 5.1.4 on 2025-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_alter_onprocess_action_alter_onprocess_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reason',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
