# Generated by Django 5.1.4 on 2025-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0040_assessment_extra_assessment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='reason',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
