# Generated by Django 5.1.4 on 2025-02-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0041_alter_assessment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
