# Generated by Django 5.1.4 on 2025-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0042_alter_waste_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semiwaste',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
