# Generated by Django 5.1.4 on 2025-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0043_alter_semiwaste_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viscosity',
            old_name='sample_no',
            new_name='reel_no',
        ),
    ]
