# Generated by Django 5.1.4 on 2025-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0044_rename_sample_no_viscosity_reel_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onprocess",
            name="sample_no",
            field=models.PositiveIntegerField(editable=False, default=1),
        ),
        migrations.AlterUniqueTogether(
            name="onprocess",
            unique_together={("assessment", "sample_no")},
        ),
    ]
