# Generated by Django 5.1.4 on 2025-03-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0045_alter_onprocess_sample_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onprocess',
            name='sample_no',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
