# Generated by Django 5.1.4 on 2025-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0046_alter_onprocess_sample_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='route_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
