# Generated by Django 5.1.4 on 2025-03-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0048_alter_lamination_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamination',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lamination', to='assessment.assessment'),
        ),
    ]
