# Generated by Django 5.1.4 on 2025-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='issuetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('IN-PROGRESS', 'IN-PROGRESS'), ('PENDING', 'PENDING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='remark',
            name='action',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('IN-PROGRESS', 'IN-PROGRESS'), ('PENDING', 'PENDING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], max_length=20),
        ),
    ]
