# Generated by Django 5.1.4 on 2025-02-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_alter_issue_options_alter_issuetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-name']},
        ),
    ]
