# Generated by Django 5.1.4 on 2025-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
