# Generated by Django 5.1.4 on 2025-02-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
