# Generated by Django 5.1.4 on 2025-02-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_department_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='issue.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='remark',
            name='action',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], max_length=20),
        ),
    ]
