# Generated by Django 5.1.4 on 2025-03-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_alter_department_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='remark',
            name='action',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='issue.department')),
            ],
            options={
                'ordering': ['name', 'no'],
            },
        ),
    ]
