# Generated by Django 5.1.4 on 2025-03-10 12:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alter_issue_status_alter_remark_action_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.DateField(default=datetime.datetime.now)),
                ('referred_to_hospital', models.BooleanField(default=False)),
                ('cause', models.TextField(max_length=200)),
                ('body_part_injured', models.CharField(max_length=75)),
                ('nature_of_injury', models.CharField(max_length=75)),
                ('employee_activity_before_incident', models.TextField(max_length=100)),
                ('tools_used_before_incident', models.TextField(max_length=100)),
                ('recommendation', models.TextField(max_length=100)),
                ('action_taken', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidents', to='issue.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidents', to='issue.location')),
                ('witness_list', models.ManyToManyField(blank=True, related_name='witnessed_incidents', to='issue.employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidents', to='issue.incidenttype')),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
    ]
