# Generated by Django 5.1.4 on 2025-03-10 12:57

import issue.models
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_incidenttype_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload Image', null=True, upload_to=issue.models.issue_image_upload_path, validators=[main.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='issue',
            name='suggestion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
