# Generated by Django 5.1.4 on 2025-03-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_issue_image_issue_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='employee_activity_before_incident',
            new_name='pre_incident_activity',
        ),
    ]
