# Generated by Django 5.1.4 on 2025-03-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_rename_employee_activity_before_incident_incident_pre_incident_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='observation',
        ),
    ]
