# Generated by Django 5.1.4 on 2025-03-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_rename_description_issue_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='time',
        ),
    ]
