# Generated by Django 5.1.4 on 2025-03-10 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_alter_incident_options_remove_incident_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date', 'time']},
        ),
        migrations.AddField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
