# Generated by Django 5.1.4 on 2025-03-13 11:42

import django.db.models.deletion
import django.db.models.functions.text
import main.validators
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, validators=[main.validators.validate_code])),
                ('approved', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('file', models.FileField(help_text='Upload artwork file', upload_to=product.models.artwork_upload_path, validators=[main.validators.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_artworks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='artworks', to='product.product')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_case_insensitive_artwork_code')],
            },
        ),
    ]
