# Generated by Django 5.1.4 on 2025-01-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.product'),
        ),
    ]
