# Generated by Django 5.1.4 on 2025-01-23 12:08

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_artwork_created_at_alter_artwork_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[product.validators.validate_code]),
        ),
    ]
