# Generated by Django 5.1.4 on 2025-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_artwork_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
