# Generated by Django 5.1.4 on 2025-01-23 13:10

import product.models
import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_artwork_approved_artwork_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.FileField(help_text='Upload artwork file', upload_to=product.models.artwork_upload_path, validators=[product.validators.validate_artwork]),
        ),
    ]
