# Generated by Django 5.1.4 on 2025-01-23 13:33

import django.db.models.deletion
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_artwork_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="created_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_artworks",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artwork",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[main.validators.validate_code],
            ),
        ),
    ]
