# Generated by Django 5.1.4 on 2025-02-06 09:23

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_artwork_created_by_alter_artwork_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="code",
            field=models.CharField(
                default=1, max_length=20, validators=[main.validators.validate_code]
            ),
            preserve_default=False,
        ),
    ]
