# Generated by Django 5.1.4 on 2025-03-07 14:27

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_artwork_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-no', 'name']},
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_case_insensitive_artwork_code'),
        ),
    ]
