# Generated by Django 5.1.4 on 2025-03-10 12:57

import main.validators
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.FileField(help_text='Upload artwork file', upload_to=product.models.artwork_upload_path, validators=[main.validators.validate_image]),
        ),
    ]
