# Generated by Django 5.1.4 on 2025-03-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(choices=[('FIRST-OFF', 'FIRST-OFF'), ('ON-PROCESS', 'ON-PROCESS')], max_length=20)),
                ('no', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
            options={
                'ordering': ['no'],
                'unique_together': {('report', 'machine')},
            },
        ),
    ]
