# Generated by Django 5.1.4 on 2025-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportheader_by_alter_reportheader_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportheader',
            name='report',
            field=models.CharField(choices=[('FIRST-OFF', 'FIRST-OFF'), ('ON-PROCESS', 'ON-PROCESS'), ('FIRE-PREVENTION', 'FIRE-PREVENTION'), ('INCIDENT', 'INCIDENT')], max_length=20),
        ),
    ]
