# Generated by Django 5.1.4 on 2025-03-26 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('report', '0003_alter_reportheader_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportheader',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportheader',
            name='effective_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 13, 18, 13, 142499)),
        ),
        migrations.AddField(
            model_name='reportheader',
            name='issue_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='reportheader',
            unique_together={('report', 'machine', 'issue_no')},
        ),
    ]
