# Generated by Django 5.1.4 on 2025-03-29 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reportheader_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportheader',
            name='effective_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 10, 47, 25, 251334)),
        ),
    ]
