# Generated by Django 5.1.4 on 2025-04-14 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reportheader_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportheader',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
