# Generated by Django 5.1.4 on 2024-12-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assesment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstofftest",
            name="value",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
