# Generated by Django 5.1.4 on 2025-01-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assesment', '0001_initial'),
        ('quality_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstoff',
            name='quality_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_off_tests', to='quality_test.qualitytest'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assesment.conformity'),
        ),
        migrations.AddField(
            model_name='onprocess',
            name='quality_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_process_conformities', to='quality_test.qualitytest'),
        ),
        migrations.AddField(
            model_name='firstoff',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assesment.test'),
        ),
    ]
