# Generated by Django 5.1.4 on 2025-01-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0006_conformity_test_onprocessconformity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conformity',
            options={'ordering': ['-id'], 'verbose_name_plural': 'conformities'},
        ),
    ]
