# Generated by Django 5.1.4 on 2025-01-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0007_alter_conformity_options'),
        ('first_off', '0011_alter_firstoff_machine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstOffTest',
            new_name='FirstOff',
        ),
        migrations.RenameModel(
            old_name='OnProcessConformity',
            new_name='OnProcess',
        ),
    ]
