# Generated by Django 5.1.4 on 2025-01-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0009_alter_customer_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tests', models.ManyToManyField(blank=True, related_name='machines', to='misc.test')),
            ],
        ),
    ]
