# Generated by Django 5.1.4 on 2025-01-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='conformities',
            field=models.ManyToManyField(blank=True, related_name='machines', to='assessment.conformity'),
        ),
        migrations.AddField(
            model_name='machine',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='machines', to='assessment.test'),
        ),
    ]
