# Generated by Django 5.1.4 on 2025-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_conformities_machine_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='viscosity_test',
            field=models.BooleanField(default=False),
        ),
    ]
