# Generated by Django 5.1.4 on 2025-01-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_route_machineroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineroute',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_routes', to='machine.machine'),
        ),
        migrations.AlterField(
            model_name='machineroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_machines', to='machine.route'),
        ),
    ]
