# Generated by Django 5.1.4 on 2025-01-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0006_conformity_test_onprocessconformity_and_more'),
        ('machine', '0003_alter_machineroute_machine_alter_machineroute_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='conformities',
            field=models.ManyToManyField(blank=True, related_name='conformities', to='assesment.test'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='machines', to='assesment.test'),
        ),
    ]
