# Generated by Django 5.1.4 on 2025-02-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machine_viscosity_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name']},
        ),
    ]
