# Generated by Django 5.1.4 on 2025-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_alter_machine_options_alter_route_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, choices=[('PRE-PRESS', 'PRE-PRESS'), ('POST-PRESS', 'POST-PRESS'), ('PRESS', 'PRESS'), ('LAMINATION', 'LAMINATION'), ('PACKAGING', 'PACKAGING')], max_length=100, null=True),
        ),
    ]
