# Generated by Django 5.1.4 on 2025-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0007_alter_conformity_options'),
        ('machine', '0004_machine_conformities_alter_machine_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='conformities',
            field=models.ManyToManyField(blank=True, related_name='conformities', to='assesment.conformity'),
        ),
    ]
