# Generated by Django 5.1.4 on 2025-03-07 14:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0049_alter_lamination_assessment'),
        ('machine', '0005_alter_machine_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machine',
            name='unique_case_insensitive_name',
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_machine_name'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_route_name'),
        ),
    ]
