# Generated by Django 5.1.4 on 2025-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_machine_conformities'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, choices=[('PRE-PRESS', 'PRE-PRESS'), ('POST-PRESS', 'POST-PRESS'), ('PRESS', 'PRESS'), ('LAMINATION', 'LAMINATION'), ('BINDER', 'BINDER'), ('PACKAGING', 'PACKAGING')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
