# Generated by Django 5.1.4 on 2025-01-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0006_machine_type_alter_machine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_routes",
                to="machine.machine",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("name", "order")},
        ),
        migrations.DeleteModel(
            name="MachineRoute",
        ),
    ]
