# Generated by Django 5.1.4 on 2025-01-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0007_route_machine_route_order_alter_route_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="machine",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to="machine.Machine",
                related_name="machine_routes",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="order",
            field=models.IntegerField(),
        ),
    ]
