# Generated by Django 5.1.4 on 2025-01-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_alter_route_machine_delete_machineroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_routes', to='machine.machine'),
        ),
    ]
