# Generated by Django 5.1.4 on 2025-01-13 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_alter_route_machine'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='route',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='route',
            name='order',
        ),
        migrations.CreateModel(
            name='MachineRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.route')),
            ],
            options={
                'unique_together': {('order', 'route')},
            },
        ),
    ]
