# Generated by Django 5.1.4 on 2025-01-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_alter_route_unique_together_remove_route_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineroute',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
    ]
