# Generated by Django 5.1.4 on 2025-01-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_alter_machineroute_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineroute',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
    ]
