# Generated by Django 5.1.4 on 2025-01-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_alter_machineroute_machine'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineroute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machineroute',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_routes', to='machine.machine'),
        ),
        migrations.AlterField(
            model_name='machineroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_machines', to='machine.route'),
        ),
        migrations.AlterUniqueTogether(
            name='machineroute',
            unique_together={('machine', 'route')},
        ),
    ]
