# Generated by Django 5.1.4 on 2025-01-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0013_alter_machineroute_unique_together_route_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineroute',
            unique_together=set(),
        ),
    ]
