# Generated by Django 5.1.4 on 2025-01-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0014_alter_machineroute_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='active',
        ),
    ]
