# Generated by Django 5.1.4 on 2025-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0015_remove_route_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
