# Generated by Django 5.1.4 on 2025-01-13 13:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0008_rename_firstofftest_firstoff_and_more'),
        ('machine', '0016_route_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_name'),
        ),
    ]
