# Generated by Django 5.1.4 on 2024-12-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_off', '0007_firstoff_inspected_by_alter_firstoff_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstOffApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approver', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('OPERATOR', 'OPERATOR'), ('INSPECTOR', 'INSPECTOR'), ('SUPERVISOR', 'SUPERVISOR')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_off.firstoff')),
            ],
        ),
    ]
