# Generated by Django 5.1.4 on 2025-01-16 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('assessment', '0006_assessment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=20)),
                ('approver', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('OPERATOR', 'OPERATOR'), ('INSPECTOR', 'INSPECTOR'), ('SUPERVISOR', 'SUPERVISOR')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FirstOffApproval',
        ),
    ]
