# Generated by Django 5.1.4 on 2025-01-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0001_initial'),
        ('quality_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstoffapproval',
            name='quality_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_test.qualitytest'),
        ),
    ]
