# Generated by Django 5.1.4 on 2024-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoffapproval',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
