# Generated by Django 5.1.4 on 2025-01-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_assessmentapproval_delete_firstoffapproval'),
        ('assessment', '0008_alter_onprocess_conformity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentapproval',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='assessment.assessment'),
        ),
    ]
