# Generated by Django 5.1.4 on 2025-03-14 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_initial'),
        ('she', '0005_alter_fpchecklist_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirePreventionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=20)),
                ('approver', models.CharField(choices=[('MANAGER', 'MANAGER'), ('SAFETY', 'SAFETY')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fire_prevention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='she.fireprevention')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
