# Generated by Django 5.1.4 on 2024-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_alter_firstoffapproval_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstoffapproval',
            name='approved',
        ),
        migrations.AddField(
            model_name='firstoffapproval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=20),
        ),
    ]
