# Generated by Django 5.1.4 on 2025-02-14 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_alter_assessmentapproval_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentapproval',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='assessmentapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentapproval',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessmentapproval',
            name='approver',
            field=models.CharField(default='SUPERVISOR', max_length=20),
        ),
    ]
