# Generated by Django 5.1.4 on 2025-04-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_firepreventionapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentapproval',
            old_name='comment',
            new_name='reason',
        ),
    ]
