# Generated by Django 5.1.4 on 2024-12-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_remove_firstoffapproval_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstoffapproval',
            old_name='approved_by',
            new_name='by',
        ),
    ]
