# Generated by Django 5.1.4 on 2025-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_rename_comment_assessmentapproval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentapproval',
            name='approver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
