# Generated by Django 5.1.4 on 2025-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('she', '0002_checkpoint_fireprevention_fpchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpchecklist',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'N/A')], default='N/A', null=True),
        ),
    ]
