# Generated by Django 5.1.4 on 2024-12-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_off', '0001_initial'),
        ('misc', '0004_paper_delete_rawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstOffTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('first_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_off.firstoff')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.test')),
            ],
        ),
    ]
