# Generated by Django 5.1.4 on 2025-01-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_current_machine_remove_job_status_and_more'),
        ('quality_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitytest',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='qualitytest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qualitytest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='qualitytest',
            name='no',
        ),
        migrations.RemoveField(
            model_name='qualitytest',
            name='paper',
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='job_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.jobtest'),
            preserve_default=False,
        ),
    ]
