# Generated by Django 5.1.4 on 2024-12-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_test', '0002_alter_firstofftest_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstofftest',
            old_name='comment',
            new_name='remark',
        ),
    ]
