# Generated by Django 5.1.4 on 2024-12-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0005_alter_firstoff_options'),
        ('quality_test', '0004_alter_firstofftest_first_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstofftest',
            name='first_off',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_off_tests', to='first_off.firstoff'),
        ),
    ]
