# Generated by Django 5.1.4 on 2025-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_paper_jobtest_raw_material'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper',
            new_name='RawMaterial',
        ),
        migrations.AddField(
            model_name='color',
            name='viscosity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
