# Generated by Django 5.1.4 on 2024-12-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
