# Generated by Django 5.1.4 on 2025-01-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_artwork_remove_job_artwork_approved_and_more'),
        ('misc', '0002_rename_paper_rawmaterial_color_viscosity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
