# Generated by Django 5.1.4 on 2024-12-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_color_code_product_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Rawmaterial',
        ),
    ]
