# Generated by Django 5.1.4 on 2025-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_standard',
        ),
        migrations.AddField(
            model_name='colorstandard',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='color_standards', to='misc.color'),
        ),
    ]
