# Generated by Django 5.1.4 on 2025-01-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_remove_color_color_standard_colorstandard_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstandard',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
