# Generated by Django 5.1.4 on 2024-12-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_paper_delete_rawmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='description',
        ),
        migrations.AddField(
            model_name='machine',
            name='code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
