# Generated by Django 5.1.4 on 2024-12-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_remove_machine_description_machine_code_machine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='type',
        ),
    ]
