# Generated by Django 5.1.4 on 2024-12-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_remove_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
