# Generated by Django 5.1.4 on 2025-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='viscosity',
            field=models.FloatField(default=0),
        ),
    ]
