# Generated by Django 5.1.4 on 2025-01-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_alter_color_viscosity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
