# Generated by Django 5.1.4 on 2024-12-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_alter_test_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='code',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='type',
        ),
    ]
