# Generated by Django 5.1.4 on 2025-01-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_alter_test_options_remove_machine_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
