# Generated by Django 5.1.4 on 2025-01-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
