# Generated by Django 5.1.4 on 2025-02-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_delete_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='colorstandard',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name']},
        ),
    ]
