# Generated by Django 5.1.4 on 2025-01-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_machine'),
        ('first_off', '0010_alter_firstoff_machine'),
        ('job', '0007_alter_job_machine'),
        ('misc', '0009_alter_customer_options_alter_product_options'),
        ('pallet', '0003_alter_palletmachine_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
