# Generated by Django 5.1.4 on 2025-01-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0010_alter_firstoff_machine'),
        ('misc', '0009_alter_customer_options_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
