# Generated by Django 5.1.4 on 2025-01-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_machine_conformities_alter_machine_tests'),
        ('misc', '0010_delete_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
