# Generated by Django 5.1.4 on 2025-03-07 14:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0011_alter_color_name_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='no',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_color_name'),
        ),
        migrations.AddConstraint(
            model_name='colorstandard',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_color_standard_name'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_RM_name'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_shift_name'),
        ),
    ]
