# Generated by Django 5.1.4 on 2025-03-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_alter_rawmaterial_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['name', 'thickness']},
        ),
        migrations.RemoveConstraint(
            model_name='rawmaterial',
            name='unique_case_insensitive_RM_name',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='no',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
