# Generated by Django 5.1.4 on 2024-12-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_color_code_product_no'),
        ('pallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletmachine',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.unit'),
        ),
    ]
