# Generated by Django 5.1.4 on 2025-01-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('pallet', '0002_palletmachine_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletmachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
    ]
