# Generated by Django 5.1.4 on 2025-01-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0003_alter_palletmachine_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletmachine',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='palletmachine',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='palletmachine',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='palletmachine',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='palletmachine',
            name='unit',
        ),
        migrations.DeleteModel(
            name='PalletCard',
        ),
        migrations.DeleteModel(
            name='PalletMachine',
        ),
    ]
