# Generated by Django 5.1.4 on 2024-12-25 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0002_job_customer'),
        ('misc', '0004_paper_delete_rawmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.BigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('batch_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.machine')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.paper')),
            ],
        ),
    ]
