# Generated by Django 5.1.4 on 2024-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoff',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
