# Generated by Django 5.1.4 on 2024-12-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0002_alter_firstoff_no'),
        ('misc', '0008_alter_test_options_remove_machine_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoff',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firstoff',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstoff',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.paper'),
        ),
        migrations.AlterField(
            model_name='firstoff',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
