# Generated by Django 5.1.4 on 2024-12-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0003_alter_firstoff_batch_no_alter_firstoff_date_and_more'),
        ('misc', '0008_alter_test_options_remove_machine_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstoff',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.shift'),
        ),
    ]
