# Generated by Django 5.1.4 on 2024-12-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0004_firstoff_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstoff',
            options={'ordering': ['-created_at']},
        ),
    ]
