# Generated by Django 5.1.4 on 2024-12-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0005_alter_firstoff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstoff',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20),
        ),
    ]
