# Generated by Django 5.1.4 on 2024-12-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0006_firstoff_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firstoff',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inspected_first_offs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firstoff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_first_offs', to=settings.AUTH_USER_MODEL),
        ),
    ]
