# Generated by Django 5.1.4 on 2024-12-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0007_firstoff_inspected_by_alter_firstoff_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoff',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20),
        ),
    ]
