# Generated by Django 5.1.4 on 2025-01-02 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0008_alter_firstoff_status'),
        ('job', '0005_alter_job_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoff',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_offs', to='job.job'),
        ),
    ]
