# Generated by Django 5.1.4 on 2025-01-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_off', '0009_alter_firstoff_job'),
        ('machine', '0003_alter_machineroute_machine_alter_machineroute_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstoff',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.machine'),
        ),
    ]
