# Generated by Django 5.1.4 on 2025-01-14 07:06

import django.db.models.deletion
import job.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('tests', models.IntegerField(default=1)),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('artwork_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF PENDING', 'FIRST-OFF PENDING'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS', 'ON-PROCESS'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=100)),
                ('artwork', models.FileField(blank=True, help_text='Upload artwork file', null=True, upload_to='artworks/', validators=[job.validators.validate_artwork])),
                ('color_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.colorstandard')),
                ('current_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_jobs', to='machine.machine')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.customer')),
                ('press_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='machine.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.product')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.route')),
            ],
            options={
                'ordering': ['-no'],
            },
        ),
    ]
