# Generated by Django 5.1.4 on 2025-03-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('misc', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('test_count', models.PositiveIntegerField(default=1)),
                ('color_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='misc.colorstandard')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='misc.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='product.product')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='machine.route')),
            ],
            options={
                'ordering': ['-no'],
            },
        ),
        migrations.CreateModel(
            name='JobTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS CREATED', 'ON-PROCESS CREATED'), ('COMPLETED', 'COMPLETED'), ('FINISHED', 'FINISHED')], default='READY', max_length=100)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_tests', to='product.artwork')),
                ('color_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tests', to='misc.colorstandard')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_tests', to=settings.AUTH_USER_MODEL)),
                ('current_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_job_tests', to='machine.machine')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tests', to='job.job')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.rawmaterial')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tests', to='machine.route')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
