# Generated by Django 5.1.4 on 2025-01-14 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('machine', '0001_initial'),
        ('misc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='current_machine',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tests',
        ),
        migrations.CreateModel(
            name='JobTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF PENDING', 'FIRST-OFF PENDING'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS', 'ON-PROCESS'), ('ON-PROCESS PENDING', 'ON-PROCESS PENDING'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=100)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_tests', to=settings.AUTH_USER_MODEL)),
                ('current_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_job_tests', to='machine.machine')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tests', to='job.job')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.paper')),
            ],
        ),
    ]
