# Generated by Django 5.1.4 on 2024-12-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('misc', '0004_paper_delete_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.customer'),
        ),
    ]
