# Generated by Django 5.1.4 on 2025-01-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_current_machine_remove_job_status_and_more'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtest',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.route'),
        ),
    ]
