# Generated by Django 5.1.4 on 2025-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtest',
            name='status',
            field=models.CharField(choices=[('READY', 'READY'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS CREATED', 'ON-PROCESS CREATED'), ('ON-PROCESS COMPLETED', 'ON-PROCESS COMPLETED'), ('COMPLETED', 'COMPLETED')], default='READY', max_length=100),
        ),
    ]
