# Generated by Django 5.1.4 on 2024-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tests',
            field=models.IntegerField(default=1),
        ),
    ]
