# Generated by Django 5.1.4 on 2025-01-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobtest_route'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtest',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='jobtest',
            name='color_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.colorstandard'),
        ),
    ]
