# Generated by Django 5.1.4 on 2025-01-02 03:33

import job.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='artwork',
            field=models.FileField(blank=True, help_text='Upload artwork file', null=True, upload_to='artwork', validators=[job.validators.validate_artwork]),
        ),
    ]
