# Generated by Django 5.1.4 on 2025-01-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobtest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtest',
            old_name='paper',
            new_name='raw_material',
        ),
    ]
