# Generated by Django 5.1.4 on 2025-01-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_paper_jobtest_raw_material'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='job',
            name='artwork_approved',
        ),
        migrations.AlterField(
            model_name='job',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
