# Generated by Django 5.1.4 on 2025-01-23 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_artwork_remove_job_artwork_approved_and_more'),
        ('machine', '0003_machine_viscosity_test'),
        ('misc', '0003_delete_product'),
        ('product', '0003_artwork_created_at_alter_artwork_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='color_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='misc.colorstandard'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='misc.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='product.product'),
        ),
        migrations.AlterField(
            model_name='job',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='machine.route'),
        ),
        migrations.AlterField(
            model_name='jobtest',
            name='color_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tests', to='misc.colorstandard'),
        ),
        migrations.AlterField(
            model_name='jobtest',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tests', to='machine.route'),
        ),
    ]
