# Generated by Django 5.1.4 on 2025-01-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF PENDING', 'FIRST-OFF PENDING'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS CREATED', 'ON-PROCESS CREATED'), ('ON-PROCESS COMPLETED', 'ON-PROCESS COMPLETED'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=100),
        ),
    ]
