# Generated by Django 5.1.4 on 2025-01-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_color_standard_alter_job_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='certificate_no',
        ),
        migrations.RemoveField(
            model_name='job',
            name='press_machine',
        ),
    ]
