# Generated by Django 5.1.4 on 2025-01-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_machine'),
        ('machine', '0017_machine_unique_case_insensitive_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='machine',
        ),
        migrations.AddField(
            model_name='job',
            name='artwork_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='current_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_jobs', to='machine.machine'),
        ),
        migrations.AddField(
            model_name='job',
            name='press_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='machine.machine'),
        ),
        migrations.AddField(
            model_name='job',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.route'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF PENDING', 'FIRST-OFF PENDING'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS', 'ON-PROCESS'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=100),
        ),
    ]
