# Generated by Django 5.1.4 on 2025-01-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_job_certificate_no_remove_job_press_machine'),
        ('product', '0007_artwork_created_by_alter_artwork_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtest',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='job_tests', to='product.artwork'),
            preserve_default=False,
        ),
    ]
