# Generated by Django 5.1.4 on 2025-02-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobtest_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtest',
            name='status',
            field=models.CharField(choices=[('READY', 'READY'), ('FIRST-OFF CREATED', 'FIRST-OFF CREATED'), ('FIRST-OFF COMPLETED', 'FIRST-OFF COMPLETED'), ('ON-PROCESS CREATED', 'ON-PROCESS CREATED'), ('COMPLETED', 'COMPLETED'), ('FINISHED', 'FINISHED')], default='READY', max_length=100),
        ),
    ]
