# Generated by Django 5.1.4 on 2025-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_jobtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='test_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobtest',
            name='no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
